[window]
opacity = 0.85
blur = true

[font]
normal = { family = "0xProto Nerd Font", style = "Regular" }
bold = { family = "0xProto Nerd Font", style = "Regular" }
italic = { family = "0xProto Nerd Font", style = "Regular" }
bold_italic = { family = "0xProto Nerd Font", style = "Regular" }
