" On Linux, this file can be called .vimrc, and on Windows it can be called _vimrc
" There may be other options for the file name, these are just the ones I use. Either way if it works, it works

" Enable syntax highlighting
syntax on

" Enable loading plugins for specific file types
filetype plugin on

" Change leader key to space
let mapleader=" "

" Use nocompatible mode
set nocompatible

" Enable statusbar postition
set ruler

" Disable swap file
set noswapfile

" Use (relative) line numbers
set number
set relativenumber

" Highlight line
set cursorline

" Disable word wrapping
set nowrap

" Set tab spacing options
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent

" Set search options
set incsearch
set hlsearch

" Set scrolloff options
set scrolloff=10
set sidescrolloff=5

" Split windows right/below
set splitright
set splitbelow

" Set search case options
set ignorecase
set smartcase

" Show last used command on statusbar
set showcmd
